# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.inpute_missing_data <- function(data, Kern, missing_indices, lambda, subject_year_indicator, g_j, i_t, inv_j_t, inv_i_t) {
    .Call('_MMM_inpute_missing_data', PACKAGE = 'MMM', data, Kern, missing_indices, lambda, subject_year_indicator, g_j, i_t, inv_j_t, inv_i_t)
}

.square_exp_cov <- function(Coords, length_scale, eta2, nugget) {
    .Call('_MMM_square_exp_cov', PACKAGE = 'MMM', Coords, length_scale, eta2, nugget)
}

.update_subject_latent <- function(data, Kern, ZI, ki, eta, psi, lambda, omega, ISigma_psi, subject_year_indicator, g_j, i_t, inv_j_t) {
    .Call('_MMM_update_subject_latent', PACKAGE = 'MMM', data, Kern, ZI, ki, eta, psi, lambda, omega, ISigma_psi, subject_year_indicator, g_j, i_t, inv_j_t)
}

