// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// inpute_missing_data
arma::field<arma::umat> inpute_missing_data(const arma::field<arma::umat> data, arma::field<arma::mat> Kern, arma::field<arma::mat> missing_indices, arma::mat lambda, arma::vec subject_year_indicator, arma::field<arma::uvec> g_j, arma::vec i_t, arma::field<arma::vec> inv_j_t, arma::field<arma::vec> inv_i_t);
RcppExport SEXP _MMM_inpute_missing_data(SEXP dataSEXP, SEXP KernSEXP, SEXP missing_indicesSEXP, SEXP lambdaSEXP, SEXP subject_year_indicatorSEXP, SEXP g_jSEXP, SEXP i_tSEXP, SEXP inv_j_tSEXP, SEXP inv_i_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::umat> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Kern(KernSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type missing_indices(missing_indicesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type subject_year_indicator(subject_year_indicatorSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type g_j(g_jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type i_t(i_tSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type inv_j_t(inv_j_tSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type inv_i_t(inv_i_tSEXP);
    rcpp_result_gen = Rcpp::wrap(inpute_missing_data(data, Kern, missing_indices, lambda, subject_year_indicator, g_j, i_t, inv_j_t, inv_i_t));
    return rcpp_result_gen;
END_RCPP
}
// square_exp_cov
NumericMatrix square_exp_cov(NumericMatrix Coords, NumericVector length_scale, double eta2, double nugget);
RcppExport SEXP _MMM_square_exp_cov(SEXP CoordsSEXP, SEXP length_scaleSEXP, SEXP eta2SEXP, SEXP nuggetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Coords(CoordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type eta2(eta2SEXP);
    Rcpp::traits::input_parameter< double >::type nugget(nuggetSEXP);
    rcpp_result_gen = Rcpp::wrap(square_exp_cov(Coords, length_scale, eta2, nugget));
    return rcpp_result_gen;
END_RCPP
}
// update_subject_latent
List update_subject_latent(arma::field<arma::umat> data, arma::field<arma::mat> Kern, arma::field<arma::umat> ZI, arma::mat ki, arma::mat eta, arma::mat psi, arma::mat lambda, arma::mat omega, arma::cube ISigma_psi, arma::vec subject_year_indicator, arma::field<arma::uvec> g_j, arma::vec i_t, arma::field<arma::vec> inv_j_t);
RcppExport SEXP _MMM_update_subject_latent(SEXP dataSEXP, SEXP KernSEXP, SEXP ZISEXP, SEXP kiSEXP, SEXP etaSEXP, SEXP psiSEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP ISigma_psiSEXP, SEXP subject_year_indicatorSEXP, SEXP g_jSEXP, SEXP i_tSEXP, SEXP inv_j_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::umat> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Kern(KernSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::umat> >::type ZI(ZISEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ki(kiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type ISigma_psi(ISigma_psiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type subject_year_indicator(subject_year_indicatorSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::uvec> >::type g_j(g_jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type i_t(i_tSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type inv_j_t(inv_j_tSEXP);
    rcpp_result_gen = Rcpp::wrap(update_subject_latent(data, Kern, ZI, ki, eta, psi, lambda, omega, ISigma_psi, subject_year_indicator, g_j, i_t, inv_j_t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MMM_inpute_missing_data", (DL_FUNC) &_MMM_inpute_missing_data, 9},
    {"_MMM_square_exp_cov", (DL_FUNC) &_MMM_square_exp_cov, 4},
    {"_MMM_update_subject_latent", (DL_FUNC) &_MMM_update_subject_latent, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_MMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
